### PR TITLE
Add populations to tables and close #25

### LINKED ISSUE #25: Add separate tabulations for additional populations

### PR DESCRIPTION
**Pull request by ptatian**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@ptatian please see my updates

**Comment by ptatian** [comment]
@maggiesu0725 OK, a few things. First, you only have to worry about the tables being created by the %Table() macro. We don't need MOEs for the tables created at the start of %All_tables(), so just ignore those Proc Tabulates. 

Second, I would rather you don't replace the existing program as we will want to keep it as is. So, please revert your previous commit and make a copy of the tables program with a new name to work on. Also, please change the name of the ODS output files so they don't overwrite the current ones. I would just append something like "_moe" to the end of the file names in the ODS statement. (Remember that, with macro variables, you need to put a . after the macro variable name to keep it from running into the text that follows, eg,

```
ods rtf file="&_dcdata_default_path\DCOLA\Prog\SOIAA2018\Tables_ipums_SOIAA_2018_&poppre._&geo._moe.rtf" 
```

Now, according to the [SAS documentation](https://go.documentation.sas.com/?cdcId=pgmsascdc&cdcVersion=9.4_3.4&docsetId=statug&docsetTarget=statug_surveyfreq_toc.htm&locale=en), Proc Surveyfreq has no format= or noseps options. It also does not accept the Class or Var statements. Those things need to be removed. 

The structure of the Tables (not Table) statement in Proc Surveyfreq is also very different than the Table statement in Proc Tabulate. The Surveyfreq version is more like the Tables statement in Proc Freq. You cross different variables by using an *. In other words, just cross the different row and column defining vars from Proc Tabulate with each other:

```
tables &colby * &by;
```

You may also need to specify some statistics as options on the tables statement. 

Please try that and see if you can get it working. Thanks!

**Comment by maggiesu0725** [comment]
@ptatian thanks, I'm not sure why we are losing cross year comparisons (most recent 5 year to 2000), must have lost it during the loop.  However I don't know why, could you take a look?

**Comment by ptatian** [comment]
@maggiesu0725 I'll take a look at this now.

**Comment by ptatian** [comment]
@maggiesu0725 Ah, OK. Now I remember. There's no sample info for the 2000 data. So, we can't get MOEs for them this way. We should just focus on the 2012-16 distributions.

**Comment by ptatian** [comment]
@maggiesu0725 Also, please change the confidence limits to 90%.

**Review by ptatian — COMMENTED** [review]
@maggiesu0725 It seems like these programs are good to finalize. Is there any additional work that you think is needed here?

**Comment by maggiesu0725** [comment]
I don't think so. Should I merge the pull request? @ptatian

**Comment by ptatian** [comment]
@maggiesu0725 Yes, that sounds good. Thanks.

**Pull request merged**
